

var gamePattern=[];
var buttonColours=["red","blue","green","yellow"];
var userClickedPattern=[];
var level=0;
var started="false";

//************BUTTON CLICK(USER ANSWER)*************
$(".btn").click(function(event){
   var userChosenColour=this.id;
   userClickedPattern.push(userChosenColour);
   playSound(userChosenColour);
   animatePress(userChosenColour);
   if(gamePattern.length===userClickedPattern.length)
   checkAnswer(userClickedPattern[userClickedPattern.length-1]);
});

//*************KEY PRESSED BY USER*****************
$(document).keydown(function(){
    if(started==="false")
    {
        started="true";
        nextSequence();
    }
});

//*********** RANDOM SEQUENCE GENERATED BY GAME********
function nextSequence(){
    var randomNumber=Math.floor(Math.random()*4);
    var randomChosenColour=buttonColours[randomNumber];
    gamePattern.push(randomChosenColour);
    animatePress(randomChosenColour);
    playSound(randomChosenColour);
    level++;
    $("h1").text("Level "+level);
}


//**************ANSWER CHECK*****************
function checkAnswer(currentLevel){
    if(gamePattern[gamePattern.length-1]===currentLevel)
    {
        var check="true";
        for(var i=0;i<gamePattern.length;i++)
        {
            if(gamePattern[i]!==userClickedPattern[i])
            {
                check="false";
                break;
            }
        }
        if(check==="true")
        {
            userClickedPattern=[];
            setTimeout(function(){nextSequence();},1000);
        }
        else
        {
            var audio=new Audio("sounds/wrong.mp3");
            audio.play();
            $("body").addClass("game-over");
            setTimeout(function(){
                $("body").removeClass("game-over");
            },200);
            $("h1").text("Game Over, Press Any Key to Restart");
            startOver();
        }
    }
    else
    {
        var audio=new Audio("sounds/wrong.mp3");
        audio.play();
        $("body").addClass("game-over");
        setTimeout(function(){
            $("body").removeClass("game-over");
        },200);
        $("h1").text("Game Over, Press Any Key to Restart");
        startOver();
    }
}

//***********START AGAIN ON WRONG ANSWER************
function startOver()
{
    level=0;
    started="false";
    gamePattern=[];
    userClickedPattern=[];
}


//   ********* SOUND AND ANIMATION**************
function playSound(name){
    var audioLink="sounds/"+name+".mp3";
    var audio= new Audio(audioLink);
    audio.play();
}
function animatePress(currentColour){
    $("#"+currentColour).addClass("pressed");
    setTimeout(function(){
        $("#"+currentColour).removeClass("pressed");
    },100)
}
